# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
           node-version: 12
      - run: npm install -g yarn
      - run: yarn add frozen-lockfile
      -  run: yarn  build
          

     
